---
- debug: msg=hello!

- include_role:
    name: prepd/postgres

- include_role:
    name: prepd/redis

# # - include_role:
#     # name: ember
# 
# - include_role:
#     name: prepd/ruby
#     vars:
#       version: '{{ ruby_version }}'
# 
# - include_role:
#     name: prepd/nodejs
#     vars:
#       nodejs_version: '6.9.0'
