# group_vars/all/default.yml
# Plain text settings can all be in this one file b/c they're not sensitive
# Vault settings are in group_vars vault files by infrastructure_env
---
### default_api
default_api_all:
  DATABASE_TEST: default_api_test
  INFRASTRUCTURE_ENV: '{{ infrastructure_env }}'

default_api_development:
  DATABASE_HOST: localhost
  DATABASE_NAME: default_development
  DATABASE_USERNAME: admin
  REDIS_URL: redis:6379/1

default_api_local:
  DATABASE_HOST: localhost
  DATABASE_NAME: default_development
  DATABASE_USERNAME: vagrant
  REDIS_URL: redis:6379/1

default_api_production:
  DATABASE_HOST: db
  DATABASE_NAME: default_production
  DATABASE_USERNAME: vagrant
  REDIS_URL: redis:6379/1
  SFTP_KEY: /data/sftp_id_rsa

default_api_staging:
  DATABASE_HOST: localhost
  DATABASE_NAME: default_development
  DATABASE_USERNAME: admin
  REDIS_URL: redis:6379/1
  SFTP_KEY: /data/sftp_id_rsa

default_api: "{{ hostvars[inventory_hostname]['default_api_' + infrastructure_env] }}"
default_api_envs: '{{ default_api_all_vault | combine(default_api_all) | combine(default_api_vault) | combine(default_api) }}'


### default_web
default_web_all:
  INFRASTRUCTURE_ENV: '{{ infrastructure_env }}'

default_web_development:
  INFRASTRUCTURE_ENV: development
  API_HOST: default-api.development.example.com

default_web_local:
  INFRASTRUCTURE_ENV: local
  API_HOST: node0.ex1.example.local

default_web_production:
  INFRASTRUCTURE_ENV: production
  API_HOST: default-api.example.com
  AWS_BUCKET: default.example.com
  AWS_REGION: us-east-1

default_web_staging:
  INFRASTRUCTURE_ENV: staging
  API_HOST: default-api-staging.example.com
  # API_HOST: default-api.staging.example.com
  AWS_BUCKET: default.staging.example.com
  AWS_REGION: ap-southeast-1

default_web: "{{ hostvars[inventory_hostname]['default_web_' + infrastructure_env] }}"
default_web_envs: '{{ default_web_all_vault | combine(default_web_all) | combine(default_web_vault) | combine(default_web) }}'
