# group_vars/development/vars.yml
---
tf_aws_region: ap-southeast-1
infrastructure_env: development

machine_env:
  locale: en_US.UTF-8
  timezone: 'Asia/Singapore'

default_api: '{{ default_api_development }}'
default_web: '{{ default_web_development }}'
