#!/usr/bin/env ansible-playbook
---
- hosts: web-servers
  tasks:
    - debug: var=playbook_dir
    - debug: var=ansible_dir
    - debug: var=prepd_dir
    - debug: var=infrastructure_env
    - debug: var=tf_dir
    - debug: var=credentials_dir
    # - include_role:
    #     name:  provision
    #     tasks_from: vpc
    #   vars:
    #     ns: pro-train
  roles:
    - prepd/nginx
