#!/usr/bin/env ansible-playbook
# NOTE: This playbook provisions:
# - two-tiered VPC with necessary subnets and security groups
# - 3 node EC2 cluster (provisioned with Docker Swarm Mode separately)
# - Elasticache (Redis) and a multi-az RDS
# - cross-AZ ELBs and updates DNS via Route53
# ./cloud-cluster.yml -e action=destroy
# NOTE: vars are located in inventory/host_vars/localhost/cloud.yml
---
- hosts: localhost
  gather_facts: false
  connection: local

  roles:
    # NOTE: vars are located in inventory/host_vars/localhost/cloud.yml
    # NOTE: takes the environment as an extra var, e.g. -e env=staging|production (default is development)
    - { role: aws, c: "cloud.{{ env | default('development') }}", mode: "{{ action | default('create') }}" }
    # - { role: aws, c: '{{ cloud.development }}', mode: "{{ action | default('create') }}" }
    # - { role: aws, c: '{{ cloud.staging }}', mode: "{{ action | default('create') }}" }
    # - { role: aws, c: '{{ cloud.production }}', mode: "{{ action | default('create') }}" }

  tasks:
    # - debug: var=cloud_defaults
    # - debug: var=cloud
    # - debug: var=development
    # - debug: 'msg={{ extra | default("ehllo") }}'
