#!/usr/bin/env ansible-playbook
# NOTE: This playbook installs and configures a docker swarm cluster on Vagrant hosts
---
- hosts: master

  pre_tasks:
    - include_vars: '{{ item }}'
      with_first_found:
         - '../../developer.yml'
         - '~/.ansible-developer.yml'

  roles:
    - { role: docker, login: yes }

  tasks:
    - name: insert ssh aliases for each node
      blockinfile:
        create: yes
        dest: ~/.zsh.after/aliases.zsh
        marker: '# {mark} ANSIBLE MANAGED BLOCK (cluster.yml)'
        block: |
          alias n1='ssh node1.local'
          alias n2='ssh node2.local'
          alias n3='ssh node3.local'


# Update configration only on the worker nodes
- hosts: nodes

  roles:
    - common
    - docker
