#!/usr/bin/env ansible-playbook
# NOTE: This playbook will not work if it is invoked with a --limit that does not include all members of the cluster
# TODO: move iface out to a var
---
- hosts: etcd:controller:worker:&kubernetes
  name: Gather facts from all controllers, workers and etcd nodes in the cluster
  tasks: []

- hosts: master:&kubernetes

  roles:
    - { role: kubernetes-master, mode: 'configure', iface: 'eth1' }


- hosts: etcd:&kubernetes

  roles:
    - { role: etcd, mode: 'configure', iface: 'eth1' }


- hosts: controller:&kubernetes

  roles:
    - { role: kubernetes-controller, mode: 'configure', iface: 'eth1' }


- hosts: worker:&kubernetes

  roles:
    - { role: kubernetes-worker, mode: 'configure', iface: 'eth1' }


- hosts: master:&kubernetes

  roles:
    - kubernetes-client
    - { role: kubernetes-master, mode: 'run' }
