#!/usr/bin/env ansible-playbook
# This playbook generates tfvars for global terraform templates
# It take values from ansible group_vars and write them as input vars to terraform templates
# NOTE: This playbook is run only against the local inventory as it is not environment specific
---
- hosts: provisioner

  roles:
    - { role: terraform, bucket: '{{ config_envs.tf_remote_state_bucket }}', region: '{{ config_envs.tf_remote_state_region }}' }
    #- { role: k8s/kops, kops_modes: [install, configure] }

  tasks:
    - name: Generate global tfvars
      blockinfile:
        create: yes
        dest: '{{ ansible_env.HOME }}/.terraform-vars.txt'
        marker: '# {mark} ANSIBLE MANAGED BLOCK (general)'
        block: |
          tf_remote_state_bucket = "{{ config_envs.tf_remote_state_bucket }}"
          tf_remote_state_region = "{{ config_envs.tf_remote_state_region }}"
