#!/usr/bin/env ansible-playbook
---
- hosts: node0.local

  vars_files: ['default.yml']

  tasks:
    - name: Build the ember app
      command: ember build dist
        args:
          chdir: '{{ project_dir }}/default-app'
    - name: Deploy the ember app to S3
      debug: msg='TODO'


- hosts: cluster-manager:&staging

  vars_files: ['../.developer.yml', 'default.yml']

  tasks:
    - name: Log in to docker registry
      docker_login:
        registry: quay.io
        username: '{{ docker_username }}'
        password: '{{ docker_password }}'

    - set_fact:
        default_api_envs_list: []
    - set_fact:
        default_api_envs_list: "{{ default_api_envs_list + [{ item['key']: item['value'] }] }}"
      with_dict: '{{ default_api_envs }}'

    - name: Spin up default Service Containers
      docker_service:
        project_name: default-api
        pull: yes
        definition:
          version: '2'
          services:
            default:
              depends_on:
                - db
                - cache
              environment: '{{ default_api_envs_list }}'
              image: 'quay.io/account/default-api:deploy'
              ports:
                - '3000:3000'
              volumes:
                - '/home/admin/data:/data'

            cache:
              image: redis

            db:
              image: postgres
              environment:
                - POSTGRES_DB={{ default_api_envs.DATABASE_NAME }}
                - POSTGRES_PASSWORD={{ default_api_envs.DATABASE_PASSWORD }}
                - POSTGRES_USER={{ default_api_envs.DATABASE_USERNAME }}

    - name: Migrate the database
      command: docker exec -t defaultapi_default_api_1 bundle exec rake db:migrate

    #- name: Seed the database
    #  command: docker exec -t recheckapi_recheck_api_1 bundle exec rake db:seed

  # TODO: Inherit from the base application for the scheduler and the resque job runner
  # my_resque:
  #   extends:
  #     service: my_rails_app
  #   command: bundle exec rake environment resque:work
  #   environment:
  #     - TERM_CHILD=1
  #     - QUEUE=device_*
