#!/usr/bin/env ansible-playbook
---
# TODO: How to install the container into a consul+swarm based cluster?
# - hosts: cluster-manager:&local
- hosts: node0.local
  vars:
    default_api_envs: '{{ default_api_all_vault | combine(default_api_all) | combine(default_api_vault) | combine(default_api) }}'

  pre_tasks:
    # - debug: 'var={{ item }}'
    #   with_items: [default_api_all_vault, default_api_all, default_api_vault, default_api]
    - set_fact:
        my_list_var: []
    - set_fact:
        my_list_var: "{{ my_list_var + [{ item['key']: item['value'] }] }}"
      with_dict: '{{ default_api_envs }}'

  tasks:
    - debug: var=my_list_var
