---
project_name: 'default'
project_dir: '{{ ansible_env.HOME }}/{{ project_name }}'
master_name: '{{ playbook_dir.split("/")[0:-1] | last }}'
data_dir: '{{ ansible_env.HOME }}/{{ master_name }}/data/{{ project_name }}'

default_api_envs: '{{ default_api_all_vault | combine(default_api_all) | combine(default_api_vault) | combine(default_api) }}'
default_app_envs: '{{ default_app_all_vault | combine(default_app_all) | combine(default_app_vault) | combine(default_app) }}'

databases:
  - { name: '{{ default_api_envs.DATABASE_NAME }}', password: '{{ default_api_envs.DATABASE_PASSWORD }}' }
  - { name: '{{ default_api_envs.DATABASE_TEST }}', password: '{{ default_api_envs.DATABASE_PASSWORD }}' }

env_apps:
  - { dir: '{{ project_dir }}/default-api', envs: '{{ default_api_envs }}' }
  - { dir: '{{ project_dir }}/default-app', envs: '{{ default_app_envs }}' }

git_account: 'git@github.com:maxcole'
git_repos:
  - { account: '{{ git_account }}', name: 'default-api', dir: '{{ project_dir }}' }
  - { account: '{{ git_account }}', name: 'default-app', dir: '{{ project_dir }}' }

ember_apps:
  - { name: 'default-app', dir: '{{ project_dir }}' }

ruby_version: 2.3.3

rails_apps:
  - { name: 'default-api', dir: '{{ project_dir }}', bundle: yes, migrate: yes, local: yes }

tmuxinator_files:
  - { name: 'default.yml', src: '{{ project_dir }}/default-api/.tmuxinator.yml' }
