#!/usr/bin/env ansible-playbook
# NOTE: This playbook installs all the application dependenices for development
# on the 'dev' machine so it is a stand-alone product
---
- hosts: dev

  pre_tasks:
    - include_vars: '../.developer.yml'

  roles:
    - common
    - yadr
    - developer
    - developer-tools


- hosts: dev:&env_local

  roles:
    - prepd
    - terraform

  tasks:
    - name: Install boto
      pip: 
        name: boto
        state: present
