#!/usr/bin/env ansible-playbook
---
- hosts: provisioner
  vars:
    project:
      parent_dir: '{{ ansible_env.HOME }}'
      name: checkout
    git:
      user: git@github.com
      account: maxcole
      repository: ptest
  roles:
    - project
