#!/usr/bin/env ansible-playbook
---
- hosts: provisioner
  vars:
    project:
      parent_dir: '{{ ansible_env.HOME }}'
      name: change-me
    git:
      user: git@github.com
      account: change-me
      repository: change-me
  roles:
    - project
