# group_vars/all/prepd.yml
# NOTE: System vars - Change these values with care!
---
ansible_dir: '{{ inventory_dir.split("/")[0:-2] | join("/") }}'

prepd_dir: '{{ ansible_dir.split("/")[0:-3] | join("/") }}'
credentials_dir: '{{ prepd_dir }}/credentials'
data_dir: '{{ prepd_dir }}/data'
kubernetes_dir: '{{ prepd_dir }}/kubernetes'
tf_dir: '{{ prepd_dir }}/terraform'

tf_components_dir: '{{ tf_dir }}/components'
tf_instances_dir: '{{ tf_dir }}/instances'
tf_modules_dir: '{{ tf_dir }}/modules'

cert_dir: '{{ data_dir }}/cert'
ssh_dir: '{{ credentials_dir }}/keys'

### 'application-*' variables
# application name comes from ~/prepd/ansible/<application_name>/application.yml
# NOTE: These variables can only be used in playbooks which include <application_name>/application.yml
application_dir: '{{ ansible_env.HOME }}/{{ application_name }}'
app_data_dir: '{{ data_dir }}/{{ application_name }}'
