#!/usr/bin/env ansible-playbook
# invoke this playbook with extra_vars -e application=name
# where name is the name of a valid application group
# TODO: finish the implementation, possibly brake into different playbooks
---
- hosts: master
  name: dump and fetch

  vars_files: ['{{ application }}/application.yml']

  tasks:
    - set_fact:
        envs: "{{ application }}_api_envs"
    - debug: var='{{ envs }}'
    - debug: var=application_name
    - debug: var=data_dir

- hosts: xmaster
  roles:
    - { role: postgres-utils, action: 'dump-and-fetch', envs: '{{ envs }}',
        sql_file: '/tmp/{{ application_name }}.sql', dest_file: '{{ data_dir }}/{{ application_name }}.sql' }


- hosts: xmaster:&local

  vars_files: ['{{ application }}/application.yml']

  roles:
    - { role: postgres-utils, action: 'restore', envs: '{{ envs }}', sql_file: '{{ data_dir }}/{{ application_name }}.sql' }
