---
- include_role:
    name: terraplate-components/aws/vpc-public-only
  vars:
    name: vpc

- include_role:
    name: terraplate-components/aws/bastion-host
  vars:
    name: vpc

- include_role:
    name: terraplate-components/aws/sg-rails
  vars:
    name: sg
